[settings]
experimental = true

[env]
EDITOR = "hx"
COLORTERM = "truecolor"
SOPS_AGE_KEY_FILE = "{{ xdg_config_home }}/sops/age/keys.txt"

[tools]
doppler = "latest"
dyff = "latest"
"github:dalance/amber" = "latest"
"github:joshmedeski/sesh" = "latest"
kubecolor = "latest"
usage = "latest"
