[settings]
experimental = true

[env]
EDITOR = "hx"
COLORTERM = "truecolor"
SOPS_AGE_KEY_FILE = "{{ xdg_config_home }}/sops/age/keys.txt"

[tools]
doppler = "latest"
dyff = "latest"
"forgejo:explosion-mental/wallust" = "latest"
"github:dalance/amber" = "latest"
"github:joshmedeski/sesh" = "latest"
"github:square/certigo" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
helm = "latest"
herdr = "latest"
krew = "latest"
kubecolor = "latest"
"npm:oxfmt" = "latest"
talosctl = "latest"
usage = "latest"
