--allow-insecure-localhost
--disable-breakpad
--disable-device-discovery
--disable-features=TabGroups
--disable-logging
--disable-smooth-scrolling
--disable-speech-input
--disk-cache-dir=/run/user/1000/google-chrome
--enable-fast-unload
--enable-gpu-rasterization
--enable-lcd-text
--enable-oop-rasterization
--enable-precache
--enable-quic
--enable-stale-while-revalidate
--enable-surfaces-for-videos
--enable-tcp-fastopen
--enable-zero-copy
--explicitly-allowed-ports=6697
--force-device-scale-factor=1
--force-gpu-rasterization
--ignore-gpu-blacklist
--no-default-browser-check
--origin-to-force-quic-on=accounts.google.com:443
--origin-to-force-quic-on=apis.google.com:443
--origin-to-force-quic-on=notifications.google.com:443
--origin-to-force-quic-on=www.google.com:443
--reduced-referrer-granularity
--use-simple-cache-backend
--use-skia-deferred-display-list
--wm-window-animations-disabled
