--allow-insecure-localhost
--disable-breakpad
--disable-device-discovery
--disable-logging
--disable-smooth-scrolling
--disable-speech-input
--enable-features=LazyFrameLoading,LazyImageLoading,FontCacheScaling,NoStatePrefetch,SpeculativeResourcePrefetching,SpeculativePreconnect,ProactiveTabFreezeAndDiscard,SimplifyHttpsIndicator
--enable-lcd-text
--enable-precache
--explicitly-allowed-ports=6697
--origin-to-force-quic-on=www.google.com:443
--origin-to-force-quic-on=accounts.google.com:443
--origin-to-force-quic-on=apis.google.com:443
--origin-to-force-quic-on=notifications.google.com:443
--enable-quic
--enable-stale-while-revalidate
--enable-tcp-fastopen
--no-default-browser-check
--reduced-referrer-granularity
--use-simple-cache-backend
--wm-window-animations-disabled
