backend              = "glx";
fading               = false;
glx-copy-from-front  = false;
glx-no-rebind-pixmap = true;
glx-no-stencil       = true;
mark-ovredir-focused = true;
mark-wmwin-focused   = true;
shadow               = true;
shadow-offset-x      = -10;
shadow-offset-y      = -8;
shadow-opacity       = 0.7;
shadow-radius        = 10;
unredir-if-possible  = true;
use-damage           = true;
vsync                = false;
xrender-sync-fence   = true;
