# -- general settings
backend = "xrender";

# -- shadow
shadow = true;
shadow-radius = 12
shadow-opacity = .75
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-exclude = [
	"class_g *?= 'polybar'",
	"class_g = 'Bspwm' && class_i = 'presel_feedback'",
];
dropdown_menu = { shadow = false; };
popup_menu    = { shadow = false; };
utility       = { shadow = false; };

# -- opacity
active-opacity = 1.0;
inactive-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = false;

opacity-rule = [
  "95:class_g = 'st-256color'",
  "95:class_g *?= 'rofi'",
];

# fading
fading = false;
fade-in-step = 0.07;
fade-out-step = 0.07;
