# -- general settings
backend = "glx";

# -- shadow
shadow = true;
shadow-radius = 12
shadow-opacity = .75
shadow-offset-x = -7;
shadow-offset-y = -7;

# -- opacity
active-opacity = 1.0;
inactive-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = false;

opacity-rule = [
  "100:class_g    = 'Google-chrome'",
  "100:class_g    = 'Nightly'",
  "100:class_g    = 'Polybar'",
  "100:class_g    = 'Slack'",
  "100:class_g    = 'code'",
  "100:class_g    = 'feh'",
  "100:class_g    = 'firefox'",
  "100:class_g    = 'mpv'",
  "100:class_g    = 'zoom'"
];

# fading
fading = false;
fade-in-step = 0.07;
fade-out-step = 0.07;
