# [colors-dark]
# alpha=0.85

[cursor]
style=underline

[main]
dpi-aware=no
selection-target=primary
include=~/.config/foot/theme.ini

font=Monaco Nerd Font Mono:pixelsize=12:antialias=true
font-bold=Monaco Nerd Font Mono:pixelsize=12:antialias=true
line-height=13px
 
[mouse]
hide-when-typing=yes

[mouse-bindings]
primary-paste=BTN_RIGHT
select-extend=none

[scrollback]
lines=10000
