# [colors-dark]
# alpha=0.85

[cursor]
style=underline

[main]
dpi-aware=no
selection-target=primary
include=~/.config/foot/theme.ini

# font=GeistMono Nerd Font:pixelsize=16
# font-bold=GeistMono Nerd Font:pixelsize=16
# line-height=17px

# font=GohuFont 14 Nerd Font Mono:pixelsize=14
# font-bold=GohuFont 14 Nerd Font Mono:pixelsize=14
# line-height=14px
 
font=Monaco Nerd Font Mono:pixelsize=14:antialias=true
font-bold=Monaco Nerd Font Mono:pixelsize=14:antialias=true
line-height=15px
 
# font=PragmataPro:pixelsize=14:antialias=true
# font-bold=PragmataPro:pixelsize=14:antialias=true
# line-height=14px
 
[mouse]
hide-when-typing=yes

[mouse-bindings]
primary-paste=BTN_RIGHT
select-extend=none

[scrollback]
lines=10000
