[colors-dark]
background=101010
foreground=B9B9B9

# Normal/regular colors (color palette 0-7)
regular0=101010  # black
regular1=7C7C7C  # red
regular2=8E8E8E  # green
regular3=A0A0A0  # yellow
regular4=686868  # blue
regular5=747474  # magenta
regular6=868686  # cyan
regular7=B9B9B9  # white

# Bright colors (color palette 8-15)
bright0=525252   # bright black
bright1=7C7C7C   # bright red
bright2=8E8E8E   # bright green
bright3=A0A0A0   # bright yellow
bright4=686868   # bright blue
bright5=747474   # bright magenta
bright6=868686   # bright cyan
bright7=F7F7F7   # bright white

# 16=fab387
# 17=f5e0dc

# selection-foreground=
# selection-background=
