[colors-dark]
background=181512
foreground=BEA492

# Normal/regular colors (color palette 0-7)
regular0=332D29  # black
regular1=8C644C  # red
regular2=746C48  # green
regular3=908A66  # yellow
regular4=646A6D  # blue
regular5=605655  # magenta
regular6=4B5C5E  # cyan
regular7=504339  # white

# Bright colors (color palette 8-15)
bright0=817267   # bright black
bright1=9F7155   # bright red
bright2=857B52   # bright green
bright3=9C956E   # bright yellow
bright4=71777A   # bright blue
bright5=656565   # bright magenta
bright6=556D70   # bright cyan
bright7=9A875F   # bright white

# 16=fab387
# 17=f5e0dc

# selection-foreground=
# selection-background=
