[colors-dark]
background=181616
foreground=C5C9C5

# Normal/regular colors (color palette 0-7)
regular0=0D0C0C  # black
regular1=C4746E  # red
regular2=8A9A7B  # green
regular3=C4B28A  # yellow
regular4=8BA4B0  # blue
regular5=A292A3  # magenta
regular6=8EA4A2  # cyan
regular7=C8C093  # white

# Bright colors (color palette 8-15)
bright0=A6A69C   # bright black
bright1=E46876   # bright red
bright2=87A987   # bright green
bright3=E6C384   # bright yellow
bright4=7FB4CA   # bright blue
bright5=938AA9   # bright magenta
bright6=7AA89F   # bright cyan
bright7=C5C9C5   # bright white

# 16=fab387
# 17=f5e0dc

# selection-foreground=
# selection-background=
