#!/bin/zsh

# -- kill
killall sxhkd
killall polybar

# -- monitors

for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
  MONITOR=$m polybar main &
done

if [ "$(hostname)" = "archx" ]; then
    bspc monitor DVI-I-1 -d 1 2
    bspc monitor DVI-D-0 -d 3 4
else
    bspc monitor -d 1 2 3 4
fi

bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true
bspc config merge_overlapping_monitors true

# -- window
bspc config focus_follows_pointer      true
bspc config border_width               1
bspc config window_gap                 10

# -- layout
bspc config automatic_scheme           alternate
bspc config split_ratio                0.50
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config top_padding                20

# -- pointer
bspc config ignore_ewmh_focus          true
bspc config click_to_focus             button1
bspc config pointer_modifier           mod4
bspc config pointer_action1            move
bspc config pointer_action2            resize_side

# -- colors
bspc config normal_border_color        "#4c566a"
bspc config active_border_color        "#4c566a"
bspc config focused_border_color       "#e5e9f0"
bspc config presel_feedback_color      "#80a1c1"

# -- rules
bspc rule -a Code desktop=^2
bspc rule -a Slack desktop=^2
bspc rule -a Google-chrome-unstable desktop=^3
bspc rule -a Nitrogen state=floating
bspc rule -a zoom state=floating

# -- autostart
polybar-launch
sxhkd &
