#!/bin/zsh

# -- KEYBINDINGS
SXHKD_SHELL=sh sxhkd -c $HOME/.config/bspwm/sxhkdrc &

# -- DESKTOPS
bspc monitor DVI-I-1 -d 1 2 3
bspc monitor DVI-D-0 -d 4 5 6
bspc config -m DVI-I-1 top_padding 20
bspc config -m DVI-D-0 top_padding 0
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

# -- WINDOW
bspc config focus_follows_pointer true
bspc config border_width 1
bspc config window_gap 15

# -- LAYOUT
bspc config automatic_scheme spiral
bspc config initial_polarity first_child
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config single_monocle true
bspc config gapless_monocle false

# -- POINTER
bspc config ignore_ewmh_focus true
bspc config click_to_focus button1
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

# -- COLORS
source "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "#4C566A"
bspc config focused_border_color "#D8DEE9"
bspc config presel_feedback_color "#4C566A"

# -- RULES
bspc rule -a Pavucontrol state=floating
bspc rule -a zoom state=floating

# -- AUTOSTART

polybar main -r &
dunst &
picom -b
$HOME/.fehbg

# vim: set ft=sh:
