#!/bin/zsh

# -- monitor and desktop setup
bspc monitor DVI-I-1 -d 1 2
bspc monitor DVI-D-0 -d 3 4

for m in $(bspc query -M); do bspc config -m $m window_gap 10; done

# -- visual options
bspc config border_width               1
bspc config top_padding                22
bspc config split_ratio                0.50
bspc config borderless_monocle         true
bspc config gapless_monocle            true

# -- additional settings
bspc config focus_follows_pointer      true
bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true
bspc config merge_overlapping_monitors true
bspc config ignore_ewmh_focus          true
bspc config click_to_focus             button1
bspc config pointer_modifier           mod4
bspc config pointer_action1            move
bspc config pointer_action2            resize_side
# -- colors
bspc config normal_border_color        "#262729"
bspc config active_border_color        "#909090"
bspc config focused_border_color       "#616161"

# -- autostart
polybar-launch
sxhkd &
