[colors.primary]
background = "#3A3A3A"
foreground = "#DCDCCC"

[colors.normal]
black   = "#333333"
red     = "#CC9393"
green   = "#EFEF87"
yellow  = "#FFD7A7"
blue    = "#C3BF97"
magenta = "#BCA3A3"
cyan    = "#93B3A3"
white   = "#F0EFD0"

[colors.bright]
black   = "#757575"
red     = "#DFAF87"
green   = "#FFFF87"
yellow  = "#FFCFAF"
blue    = "#D7D7AF"
magenta = "#D7AFAF"
cyan    = "#93BEA3"
white   = "#DCDCCC"
