[colors.primary]
background = "#1B1D1F"
foreground = "#D8DDD4"

[colors.normal]
black   = "#1B1D1F"
red     = "#676D70"
green   = "#7D9078"
yellow  = "#A1A69E"
blue    = "#8D9497"
magenta = "#969B99"
cyan    = "#ACB2AE"
white   = "#D6D8D3"

[colors.bright]
black   = "#3B4042"
red     = "#80888B"
green   = "#9FB297"
yellow  = "#C0C5BC"
blue    = "#AEB5B8"
magenta = "#B7BCBA"
cyan    = "#CFD4D0"
white   = "#F3F4F2"
