[colors.primary]
background = "#18181B"
foreground = "#ADADB9"

[colors.normal]
black   = "#222225"
red     = "#CD5C60"
green   = "#6FB593"
yellow  = "#80BCB6"
blue    = "#4D9391"
magenta = "#AB98B5"
cyan    = "#53736A"
white   = "#919A9C"

[colors.bright]
black   = "#303035"
red     = "#CD5C60"
green   = "#6FB593"
yellow  = "#80BCB6"
blue    = "#4D9391"
magenta = "#AB98B5"
cyan    = "#53736A"
white   = "#E6E6E8"
