"attributes" = "base09"
"comment" = { fg = "base03", modifiers = ["italic"] }
"constant" = "base09"
"constant.character.escape" = "base0C"
"constant.numeric" = "base09"
"constructor" = "base08"
"debug" = "base03"
"diagnostic" = { modifiers = ["underlined"] }
"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diff.delta" = "base09"
"diff.minus" = "base08"
"diff.plus" = "base0B"
"error" = "base0D"
"function" = "base08"
"hint" = "base03"
"info" = "base08"
"keyword" = "base0E"
"label" = "base0E"
"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.heading" = "base08"
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.link.text" = "base0D"
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.list" = "base0D"
"markup.quote" = "base0C"
"markup.raw" = "base0B"
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"namespace" = "base0E"
"operator" = "base05"
"special" = "base08"
"string" = "base0B"
"type" = "base0A"
"ui.background" = { bg = "base00" }
"ui.bufferline" = { fg = "base03", bg = "base00" }
"ui.bufferline.active" = { fg = "base05", bg = "base02", modifiers = ["bold"] }
"ui.cursor" = { fg = "base04", modifiers = ["reversed"] }
"ui.cursor.insert" = { fg = "base0A", modifiers = ["underlined"] }
"ui.cursor.match" = { fg = "base0A", modifiers = ["underlined"] }
"ui.cursor.select" = { fg = "base0A", modifiers = ["underlined"] }
"ui.cursorline.primary" = { fg = "base05", bg = "base01" }
"ui.gutter" = { bg = "base00" }
"ui.help" = { fg = "base06", bg = "base01" }
"ui.linenr" = { fg = "base03", bg = "base00" }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"] }
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.scroll" = { fg = "base03", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.popup" = { bg = "base01" }
"ui.selection" = { bg = "base02" }
"ui.selection.primary" = { bg = "base02" }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.statusline.inactive" = { bg = "base01", fg = "base02" }
"ui.statusline.insert" = { fg = "base00", bg = "base0B" }
"ui.statusline.normal" = { fg = "base00", bg = "base08" }
"ui.statusline.select" = { fg = "base00", bg = "base0E" }
"ui.text" = "base05"
"ui.text.focus" = "base05"
"ui.virtual.indent-guide" = { fg = "base03" }
"ui.virtual.ruler" = { bg = "base01" }
"ui.virtual.whitespace" = { fg = "base01" }
"ui.window" = { bg = "base01" }
"variable" = "base05"
"variable.other.member" = "base0D"
"warning" = "base09"

[palette]
base00 = "#101011" # background
base01 = "#27272a" # dark gray
base02 = "#353539" # gray
base03 = "#464649" # light gray
base04 = "#909095" # secondary
base05 = "#b8b8ba" # foreground
base06 = "#c0c0c4" # lighter gray
base07 = "#b8b8ba" # white
base08 = "#bf678f" # red
base09 = "#808084" # orange
base0A = "#a277a3" # yellow
base0B = "#468b8b" # green
base0C = "#4c8299" # cyan
base0D = "#6188b3" # blue
base0E = "#8976ae" # magenta
base0F = "#959081" # brown

