# Retina Helix Theme
# Based on VSCode theme "Retina" by RafaCMur

attributes = "#5ad4e6"
constant = "#948ae3"
"constant.character.escape" = "#948ae3"
"constant.numeric" = "#948ae3"
constructor = "#7bd88f"
debug = "#dddddd"
"diff.delta" = "#e6c64f"
"diff.minus" = "#fc618d"
"diff.plus" = "#7bd88f"
error = "#fc618d"
function = "#7bd88f"
hint = "#948ae3"
info = "#5ad4e6"
keyword = "#fc618d"
label = "#948ae3"
"markup.heading" = "#e6c64f"
"markup.link.text" = "#fc618d"
"markup.list" = "#dddddd"
"markup.quote" = "#6b6a6c"
"markup.raw" = "#fd9353"
namespace = "#5ad4e6"
operator = "#fc618d"
special = "#fd9353"
string = "#e6c64f"
type = "#5ad4e6"
"ui.text" = "#dddddd"
"ui.text.focus" = "#dddddd"
variable = "#dddddd"
"variable.other.member" = "#fc618d"
warning = "#fd9353"

# Modifiers for syntax elements
[comment]
fg = "#6b6a6c"
modifiers = ["italic"]

[diagnostic]
modifiers = ["underlined"]

["diagnostic.error".underline]
style = "curl"

["diagnostic.hint".underline]
style = "curl"

["diagnostic.info".underline]
style = "curl"

["diagnostic.warning".underline]
style = "curl"

# Markup styling
["markup.bold"]
fg = "#e6c64f"
modifiers = ["bold"]

["markup.italic"]
fg = "#948ae3"
modifiers = ["italic"]

["markup.link.url"]
fg = "#7bd88f"
modifiers = ["underlined"]

["markup.strikethrough"]
modifiers = ["crossed_out"]

# UI elements
["ui.background"]
fg = "#dddddd"
bg = "#1c1c1c"

["ui.bufferline"]
bg = "#1c1c1c"
fg = "#8b888f"

["ui.bufferline.active"]
bg = "#1c1c1c"
fg = "#e6c64f"
modifiers = ["bold"]

["ui.bufferline.modified"]
bg = "#1c1c1c"
fg = "#e6c64f"
# No direct 'underline' for modified in Helix, but `activeModifiedBorder` is

["ui.cursor"]
fg = "#dddddd"
modifiers = ["reversed"]

["ui.cursor.insert"]
fg = "#dddddd"
modifiers = ["underlined"]

["ui.cursor.match"]
fg = "#e6c64f"
modifiers = ["underlined"]

["ui.cursor.select"]
fg = "#e6c64f"
modifiers = ["underlined"]

["ui.cursorline.primary"]
bg = "#dddddd0c"
fg = "#dddddd"

["ui.gutter"]
bg = "#1c1c1c"

["ui.help"]
bg = "#363537"
fg = "#bab6c0"

["ui.linenr"]
bg = "#1c1c1c"
fg = "#525053"

["ui.linenr.selected"]
bg = "#dddddd0c"
fg = "#bab6c0"
modifiers = ["bold"]

["ui.menu"]
bg = "#363537"
fg = "#bab6c0"

["ui.menu.scroll"]
bg = "#363537"
fg = "#8b888f"

["ui.menu.selected"]
bg = "#6b6a6c"
fg = "#dddddd"

["ui.popup"]
bg = "#363537"

["ui.selection"]
bg = "#bab6c026"

["ui.selection.primary"]
bg = "#bab6c026"

["ui.statusline"]
bg = "#191919"
fg = "#6b6a6c"

["ui.statusline.inactive"]
bg = "#191919"
fg = "#6b6a6c"

["ui.statusline.insert"]
bg = "#7bd88f"
fg = "#1c1c1c"

["ui.statusline.normal"]
bg = "#fc618d"
fg = "#1c1c1c"

["ui.statusline.select"]
bg = "#948ae3"
fg = "#1c1c1c"

["ui.virtual.indent-guide"]
fg = "#363537"

["ui.virtual.ruler"]
bg = "#525053"

["ui.virtual.whitespace"]
fg = "#525053"

["ui.window"]
bg = "#1c1c1c"
