alias ..='cd ..'
alias abs='asp'
alias cp='cp -i'
#alias de='xrandr --output DVI-I-1 --mode 1920x1080 --rate 144 --left-of DVI-D-0 && bspc desktop 1 -m DVI-I-1 && bspc desktop 2 -m DVI-I-1 && bspc desktop Desktop -r'
#alias ds='xrandr --output DVI-I-1 --off && bspc monitor -o 1 2 3 4 DVI-D-0'
alias de='xrandr --output DVI-I-1 --mode 1920x1080 --rate 144 --left-of DVI-D-0'
alias ds='xrandr --output DVI-I-1 --off'
alias k='kubectl'
alias l='ls -lhg'
alias la='ls -lah'
alias ls='ls --color=always --group-directories-first'
alias mkdir='mkdir -p -v'
alias mtr='sudo TERM=linux-m mtr'
alias poweroff='sudo systemctl poweroff'
alias reboot='sudo systemctl reboot'
alias reload='. ~/.zshrc'
alias remove='sudo pacman -Rscu'
alias s='sudo systemctl'
alias t='terraform'
alias ta='terraform apply'
alias taa='terraform apply -auto-approve'
alias tf='terraform format'
alias ti='terraform init --backend=false'
alias tii='terraform init'
alias tim='terraform import'
alias to='terraform output'
alias tp='terraform plan'
alias ts='terraform show'
alias tst='terraform state'
alias tv='terraform validate'
alias tw='terraform workspace'
alias tmux='tmux -2'
if [[ "$OSTYPE" == "darwin"*  ]]; then alias u='brew update && brew upgrade && brew cleanup'; fi
if [[ "$OSTYPE" == "linux-gnu" ]]; then alias u='yay -Syu --editmenu'; fi
alias virsh='/usr/bin/virsh -c qemu:///system'
alias vm='virsh start win10'
alias vpn='sudo openconnect --protocol=gp $GP_HOST'
alias x='startx'
alias xrefresh='xrdb load ~/.Xresources && xrdb -merge ~/.Xresources'
alias yay='yay --editmenu'
alias v='nvim'
alias vim='nvim'
alias v.='nvim .'
alias vv='nvim ~/.dotfiles/nvim/.config/nvim/init.vim'
alias pa='eval $(fc -ln -1 | sed "s/plan/apply/g")'
alias pa='eval $(fc -ln -1 | sed "s/apply/plan/g")'
