#!/bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor DisplayPort-0 -d 1 2
bspc monitor HDMI-A-0 -d 3 4
bspc monitor eDP -d 1 2 3 4 5

bspc config pointer_motion_interval 7ms
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config normal_border_color "#202020"
bspc config focused_border_color "#454545"

bspc rule -a "*:floating" state=floating
bspc rule -a pavucontrol state=floating

pgrep -x polybar >/dev/null || polybar -r main &
feh --bg-fill ~/.wallpapers/arch-gray.png &
xgamma -gamma 1.08 &
