#!/bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor DisplayPort-0 -d 1 2
bspc monitor HDMI-A-0 -d 3 4
bspc monitor eDP -d 1 2 3 4 5

bspc config pointer_motion_interval 7ms
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width 3
bspc config window_gap 0
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

# retina
bspc config normal_border_color "#202020"
bspc config focused_border_color "#454545"

# tokyonight
# bspc config normal_border_color "#32344a"
# bspc config focused_border_color "#444b6a"

bspc rule -a "*:floating" state=floating
bspc rule -a pavucontrol state=floating

pgrep -x polybar >/dev/null || polybar -r main &
# xsetroot -solid "#333333"
~/.fehbg &
xgamma -gamma 1.08 &
export GDK_DPI_SCALE=0.9
