# -- OPTIONS

# screen mode
set -g default-terminal "screen-256color"

# windows/panes: start with 1
set -g base-index 1
set -g pane-base-index 1

# renumber windows after closing
set -g renumber-windows on

# remove esc delay
set -sg escape-time 0

# history
set -g history-limit 100000

# allow terminal scrolling
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

# resizing
setw -g aggressive-resize on

# bell
set -g visual-activity on
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# pleb mode
#set -g mouse on

# -- KEYBINDINGS

# change prefix to ctrl+x
unbind C-b
set -g prefix C-x
bind C-x send-prefix

# vim style copy paste mode
unbind [
bind Escape copy-mode
unbind p
bind p paste-buffer
bind-key -Tcopy-mode-vi 'v' send -X begin-selection
bind-key -Tcopy-mode-vi 'y' send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# use xterm keycodes
setw -g xterm-keys on

# splitting
unbind %
bind | split-window -h
unbind '"'
bind - split-window -v

# window switching
bind-key -n C-S-left prev
bind-key -n C-S-right next
#bind-key -n S-C-left swap-window -t -1
#bind-key -n S-C-right swap-window -t +1

# window management
bind n new-window
bind tab next-window
bind t command-prompt "rename-window %%"
bind m choose-window
bind a choose-session

# colon :
bind : command-prompt

# sync panes
bind v setw synchronize-panes on
bind b setw synchronize-panes off

# map vi and arrow keys as pane movement keys
bind -n S-Left select-pane -L
bind -n S-Right select-pane -R
bind -n S-Up select-pane -U
bind -n S-Down select-pane -D
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# resize panes using H, J, K, L
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

# resize panes using up, down, left, right
bind up resize-pane -U 5
bind down resize-pane -D 5
bind left resize-pane -L 5
bind right resize-pane -R 5

# layouts
bind X next-layout
bind Z previous-layout

# reload config
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# -- THEME

# panes
set -g pane-border-style "fg=colour0"
set -g pane-active-border-style "fg=colour0"

# status bar
set -g status-bg black
set -g status-fg default
set -g status-justify "left"
set -g status "on"
set -g status-interval 2

# windows
#set -g window-active-style 'bg=colour236'
#set -g window-style 'bg=black'
set -g set-titles on
set -g set-titles-string '[#S:#I] #W'
setw -g automatic-rename on
setw -g window-status-current-format "#[fg=black,bg=green] #I #[fg=default,bg=black] #W"
setw -g window-status-format "#[fg=black,bg=blue] #I #[fg=white,bg=black] #W"

# left side
set -g status-left ""

# right side
set -g status-right-length 100
set -g status-right ""
#set -g status-right "#[fg=blue,bg=black]TIME: #[default]%r"
