# -- OPTIONS

# screen mode
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm*:Tc"
set -ga terminal-overrides ",rxvt*:Tc"
set -ga terminal-overrides ",screen*:Tc"
set -ga terminal-overrides ",tmux*:Tc"
set -ga terminal-overrides ",alacritty*:Tc"
set -ga terminal-overrides ",st*:Tc"

# windows/panes: start with 1
set -g base-index 1
set -g pane-base-index 1

# renumber windows after closing
set -g renumber-windows on

# remove esc delay
set -sg escape-time 0

# history
set -g history-limit 100000

# resizing
setw -g aggressive-resize on

# bell
set -g visual-activity on
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# pleb mode
#set -g mouse on

# -- KEYBINDINGS

# change prefix to ctrl+x
unbind C-b
set -g prefix C-x
bind C-x send-prefix

# vim style copy paste mode
unbind [
bind Escape copy-mode
unbind p
bind p paste-buffer
bind-key -Tcopy-mode-vi 'v' send -X begin-selection
bind-key -Tcopy-mode-vi 'y' send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# use xterm keycodes
setw -g xterm-keys on

# splitting
unbind %
bind | split-window -h
unbind '"'
bind - split-window -v

# window switching
bind-key -n M-q prev
bind-key -n M-e next

# window management
bind n new-window
bind tab next-window
bind t command-prompt "rename-window %%"
bind m choose-window
bind a choose-session

# colon :
bind : command-prompt

# toggle sync panes
bind v setw synchronize-panes\; display "Sync panes is now #{?pane_synchronized,on,off}!"

# map vi and arrow keys as pane movement keys
bind -n S-Left select-pane -L
bind -n S-Right select-pane -R
bind -n S-Up select-pane -U
bind -n S-Down select-pane -D
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# resize panes using H, J, K, L
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

# resize panes using up, down, left, right
bind up resize-pane -U 5
bind down resize-pane -D 5
bind left resize-pane -L 5
bind right resize-pane -R 5

# layouts
bind X next-layout
bind Z previous-layout

# reload config
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Smart pane switching with awareness of Vim splits and fzf.
# See: https://github.com/christoomey/vim-tmux-navigator
not_tmux="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?(g?(view|n?vim?x?)(diff)?|fzf)$'"
bind-key -n C-h if-shell "$not_tmux" "send-keys C-h"  "select-pane -L"
bind-key -n C-j if-shell "$not_tmux" "send-keys C-j"  "select-pane -D"
bind-key -n C-k if-shell "$not_tmux" "send-keys C-k"  "select-pane -U"
bind-key -n C-l if-shell "$not_tmux" "send-keys C-l"  "select-pane -R"
bind-key -T copy-mode-vi C-h select-pane -L
bind-key -T copy-mode-vi C-j select-pane -D
bind-key -T copy-mode-vi C-k select-pane -U
bind-key -T copy-mode-vi C-l select-pane -R

# -- THEME

# panes
set -g pane-border-style "fg=colour0"
set -g pane-active-border-style "fg=colour0"

# status bar
set -g status-bg black
set -g status-fg default
set -g status-justify "left"
set -g status "on"
set -g status-interval 2

# windows
set -g set-titles off
setw -g window-status-current-format "#[fg=black,bg=green] #I #[fg=default,bg=black] #W"
setw -g window-status-format "#[fg=black,bg=blue] #I #[fg=white,bg=black] #W"

# left side
set -g status-left ""

# right side
set -g status-right-length 100
set -g status-right ""
set -g status-right "#(/bin/bash $HOME/.tmux/kube.tmux white cyan) #[fg=blue,bg=black]TIME: #[default]%r"

# -- PLUGINS

# list of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

# initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
