export BAT_THEME="base16"
export CLICOLOR=1
export CORRECT_IGNORE_FILE='.*'
export EDITOR=nvim
export FZF_DEFAULT_COMMAND='fd'
# export FZF_DEFAULT_OPTS='--color fg:#D8DEE9,bg:#2E3440,hl:#A3BE8C,fg+:#D8DEE9,bg+:#434C5E,hl+:#A3BE8C --color pointer:#BF616A,info:#4C566A,spinner:#4C566A,header:#4C566A,prompt:#81A1C1,marker:#EBCB8B'
export FZF_DEFAULT_OPTS='--color fg:#C6C8D1,bg:#161821,hl:#E9B189,fg+:#C6C8D1,bg+:#22262E,hl+:#E9B189 --color pointer:#BF616A,info:#4C566A,spinner:#4C566A,header:#4C566A,prompt:#91ACD1,marker:#EBCB8B'
export GOPATH=~/go
export GREP_COLOR="1;31"
export HISTFILE=~/.zhistory
export HISTSIZE='10000'
export INFRACTL_CHECK_VERSION=false
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_COLLATE="C"
export LESS=" -R"
export LESSOPEN="| highlight %s --out-format xterm256 --force --style=nord"
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'
export LOCALE=en_US.UTF-8
export MOZ_DISABLE_PANGO=1
export PAGER="less -iMR"
export VISUAL=nvim
export ZSH_CACHE_DIR=$HOME/.cache
export QT_SCALE_FACTOR_ROUNDING_POLICY=Round
