rootcolor=0x{{ color4 | strip }}FF
bordercolor=0x{{ color0 | strip }}FF
focuscolor=0x{{ color7 | strip }}FF
maximizescreencolor=0x{{ color2 | strip }}FF
urgentcolor=0x{{ color1 | strip }}FF
scratchpadcolor=0x{{ color5 | strip }}FF
globalcolor=0x{{ color4 | strip }}FF
overlaycolor=0x{{ color6 | strip }}FF
