[general]
import = ["~/.config/alacritty/themes/retina.toml"]

[env]
TERM = "xterm"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 12.5
offset.y = -5
offset.x = -1

[font.normal]
# family = "Gohu Gohufont"
family = "BerkeleyMono Nerd Font Mono"
style = "Regular"

[font.bold]
style = "Regular"

[mouse]
bindings = [
{ mouse = "Right", action = "PasteSelection" }
]

[selection]
save_to_clipboard = true

[window]
padding = { x = 8, y = 6 }
