[general]
import = ["~/.config/alacritty/themes/retina.toml"]

[env]
# TERM = "xterm-color"
WINIT_X11_SCALE_FACTOR = "0.95"

[font]
size = 13.5
offset.y = -5
offset.x = -1

[font.normal]
# family = "Gohu Gohufont"
family = "BerkeleyMono Nerd Font Mono"
style = "Regular"

[font.bold]
style = "Regular"

[mouse]
bindings = [
{ mouse = "Right", action = "PasteSelection" }
]

[selection]
save_to_clipboard = true

[window]
padding = { x = 0, y = 0 }

[[keyboard.bindings]]
chars = "\u0018T"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018L"
key = "L"
mods = "Alt"

