[general]
import = ["~/.config/alacritty/themes/tokyo_night.toml"]

# [env]
# WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 9
offset.y = -1
# offset.x = -1

[font.normal]
# family = "MonoLisa"
# family = "Gohu Gohufont"
family = "Terminus"
# family = "BerkeleyMono Nerd Font Mono"
style = "Regular"

[font.bold]
style = "Regular"

[mouse]
bindings = [
{ mouse = "Right", action = "PasteSelection" }
]

[selection]
save_to_clipboard = true

[window]
padding = { x = 0, y = 0 }

[[keyboard.bindings]]
chars = "\u0018T"
key = "O"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018L"
key = "P"
mods = "Alt"

