[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 12.0
offset.y = -3

[font.normal]
family = "Terminus"
style = "Regular"

[font.bold]
style = "Regular"

[mouse]
bindings = [
{ mouse = "Right", action = "PasteSelection" }
]

[selection]
save_to_clipboard = true

[window]
padding = { x = 8, y = 6 }
