[general]
import = ["~/.config/alacritty/themes/retina.toml"]

[env]
# TERM = "xterm-color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 13.5
offset.y = -4
offset.x = -1

[font.normal]
# family = "Gohu Gohufont"
family = "BerkeleyMono Nerd Font Mono"
style = "Regular"

[font.bold]
style = "Regular"

[mouse]
bindings = [
{ mouse = "Right", action = "PasteSelection" }
]

[selection]
save_to_clipboard = true

[window]
padding = { x = 8, y = 6 }
