[language-server.uwu-colors]
command = "uwu_colors"

[language-server.yaml-language-server.config]
yaml.completion = true
yaml.validation = true
yaml.hover = true
# yaml.schemaStore.enable = true # Uncomment if you want to enable schema store

[language-server.yaml-language-server.config.yaml.schemas]
# ansible tasks
"https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks" = "tasks/*.{yml,yaml}"

# ansible playbooks
"https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/playbook" = "*ansible*/*.{yml,yaml}"

# kustomization
"http://json.schemastore.org/kustomization" = "kustomization.{yml,yaml}"

# helm chart
"http://json.schemastore.org/chart" = "Chart.{yml,yaml}"

# helmfile
"http://json.schemastore.org/helmfile.json" = "helmfile.{yml,yaml}"

# gitlab-ci
"https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json" = "*gitlab-ci*.{yml,yaml}"

# argo workflows
"https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/jsonschema/schema.json" = "*flow*.{yml,yaml}"

# taskfile
"http://json.schemastore.org/taskfile.json" = "Taskfile*.{yml,yaml}"

# kubernetes
# "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.30.0/all.json" = "/*.yaml"

# github workflow
"http://json.schemastore.org/github-workflow" = ".github/workflows/*"

# github actions
"http://json.schemastore.org/github-action" = ".github/action.{yml,yaml}"

# flux kustomization
"https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json" = "ks.{yml,yaml}"

# flux helmrelease
"https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json" = "helmrelease.{yml,yaml}"

# externalsecrets
"https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json" = "external*secret.{yml,yaml}"


[[language]]
name = "bash"
auto-format = true

[language.formatter]
command = "shfmt"
args = ["-i", "2", "-ci"]

[[language]]
name = "fish"
language-servers = ["fish-lsp", "uwu-colors"]

[[language]]
name = "go"
auto-format = true

[language.formatter]
command = "goimports"
args = ["-local", "github.com/core"]

[language.indent]
tab-width = 2
unit = "\t"

[[language]]
name = "json"
auto-format = true

[language.formatter]
command = "fixjson"

[[language]]
name = "markdown"
auto-format = true

[language.formatter]
command = "deno"
args = ["fmt", "-", "--ext", "md"]

[[language]]
name = "nix"
auto-format = true

[language.formatter]
command = "alejandra"

[[language]]
name = "python"
language-servers = ["pyright"]
auto-format = true

[language.formatter]
command = "black"
args = ["--quiet", "-"]
